import time 
print("|          |",end="\r")
time.sleep(1)
print("|=>        |",end="\r")
time.sleep(1)
print("|==>       |",end="\r")
time.sleep(1)
print("|===>      |",end="\r")
time.sleep(1)
print("|====>     |",end="\r")
time.sleep(1)
print("|=====>    |",end="\r")
time.sleep(1)
print("|======>   |",end="\r")
time.sleep(1)
print("|=======>  |",end="\r")
time.sleep(1)
print("|========> |",end="\r")
time.sleep(1)
print("|==========|",end="\r")
print("\n Done!")